### ISSUE TITLE
Fuzz Testing - Theory and practice

### ISSUE THREAD

**Issue by fernandezpablo85** [papers-we-love/buenos-aires#2]
## Theory

* Introduction to Fuzz Testing [Miller 89](https://dl.acm.org/citation.cfm?id=96279): What is Fuzz Testing? Why is it important? bugs (and their causes) found in the study.

* Subsequent studies on same tools, different platforms: [Miller 95](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.363.2901&rep=rep1&type=pdf), [Miller 02](http://pages.cs.wisc.edu/~bart/fuzz/fuzz-nt.html). Same tests repeated on Linux and Windows NT.

## Practice

* From Fuzz Testing to Property-Based Testing.

* Using [Hypothesis](http://hypothesis.works) to test Python programs.

**Comment by unbalancedparentheses** [comment]
I am a big fan of property based testing too! Let's after the first meetup and we can start organizing a second meetup where you give a talk about this.

**Comment by unbalancedparentheses** [comment]
@fernandezpablo85 Pablo, would you be able to give the talk in the next few weeks?

**Comment by fernandezpablo85** [comment]
Hi, I'm actually speaking in [nerdearla](https://nerdearla2019.eventbrite.com) this weekend so I'm a bit focused on that talk. Will try to put up some slides for this one in the coming weeks. Thanks

**Comment by fernandezpablo85** [comment]
Hi, an update on this. I actually pulled the talk off (here are the [slides & code](https://github.com/fernandezpablo85/fuzz_talk)) but it ended up being a lot more pragmatic and less focused on the literature. I don't think it's a good fit with the spirit of the meetup so I'm closing this. 

Feel free to reopen if you check the slides and think otherwise.

Thanks.
